/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.modelo.Cliente;
import java.util.ResourceBundle;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class VentanaListarCliente extends javax.swing.JInternalFrame {
 private ControladorCliente controladorCliente;
 private ResourceBundle mensajes;
    /**
     * Creates new form ListarClientes
     */
    public VentanaListarCliente(ControladorCliente controladorCliente,ResourceBundle mensajes) {
        initComponents();
        this.controladorCliente=controladorCliente;
        this.mensajes = mensajes ;
        llenarDatos();
        cambiarIdioma( mensajes );
    }
     public void cambiarIdioma(ResourceBundle mensajes ){
   
   jlbTituloListaCliente.setText(mensajes.getString("Ventana.Listar.Cliente"));
   
   }
    public void llenarDatos(){
        DefaultTableModel modelo=(DefaultTableModel)tblCliente.getModel();
        Set<Cliente>lista=controladorCliente.getLista();
        for(Cliente cliente:lista){
            Object[]datos={cliente.getCodigo(),
                cliente.getCedula(),cliente.getNombre(),
                cliente.getDireccion(),cliente.getTelefono()};
            
             modelo.addRow(datos);
            
        }
        
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jlbTituloListaCliente = new javax.swing.JLabel();

        setClosable(true);

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cedula", "Nombre", "Direccion", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(tblCliente);

        jlbTituloListaCliente.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbTituloListaCliente.setText("LISTA CLIENTES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jlbTituloListaCliente)
                .addContainerGap(342, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTituloListaCliente)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbTituloListaCliente;
    private javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables
}
